## sklearn

In [3]:
import numpy as np
from sklearn.decomposition import NMF as SKNMF

X = np.array([[1, 2], [2, 2], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
model = SKNMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_

In [4]:
print("X (Orginal matrix):")
print(X)
print("\nW (basis matrix):")
print(W)
print("\nH (coefficient matrix):")
print(H)    
X_hat = np.dot(W, H)
print("\nX_hat (Reconstructed matrix):")
print(X_hat)

X (Orginal matrix):
[[1.  2. ]
 [2.  2. ]
 [3.  1.2]
 [4.  1. ]
 [5.  0.8]
 [6.  1. ]]

W (basis matrix):
[[0.         0.80819704]
 [0.49493882 0.74610925]
 [1.18847642 0.33562571]
 [1.73330963 0.18632835]
 [2.27818266 0.03701297]
 [2.72390595 0.0618278 ]]

H (coefficient matrix):
[[2.17463514 0.31094941]
 [1.23767438 2.47446779]]

X_hat (Reconstructed matrix):
[[1.00028477 1.99985754]
 [1.99975165 2.00012424]
 [2.99989794 1.20005106]
 [3.99992985 1.00003509]
 [5.00002608 0.79998695]
 [6.00002429 0.99998785]]


## torchnmf

In [7]:
import torch
from torchnmf.nmf import NMF as TNMF

# Convert to torch tensor
X_torch = torch.from_numpy(X).float()

# Initialize the NMF model with desired rank (number of components)
rank = 2
model = TNMF(X_torch.shape, rank=rank)

In [8]:
print("X (Orginal matrix):")
print(X_torch)
print("\nW (basis matrix):")
print(model.W)
print("\nH (coefficient matrix):")
print(model.H)    
X_hat = np.dot(W, H)
print("\nX_hat (Reconstructed matrix):")
print(X_hat)

X (Orginal matrix):
tensor([[1.0000, 2.0000],
        [2.0000, 2.0000],
        [3.0000, 1.2000],
        [4.0000, 1.0000],
        [5.0000, 0.8000],
        [6.0000, 1.0000]])

W (basis matrix):
Parameter containing:
tensor([[1.0144, 0.0661],
        [2.3521, 1.0846]], requires_grad=True)

H (coefficient matrix):
Parameter containing:
tensor([[1.9634, 0.0068],
        [0.1179, 1.0722],
        [0.6458, 1.2312],
        [0.5012, 0.4947],
        [0.4491, 0.2019],
        [1.2510, 0.3422]], requires_grad=True)

X_hat (Reconstructed matrix):
[[1.00028477 1.99985754]
 [1.99975165 2.00012424]
 [2.99989794 1.20005106]
 [3.99992985 1.00003509]
 [5.00002608 0.79998695]
 [6.00002429 0.99998785]]


## nmftorch

In [ ]:
from nmf import run_nmf

In [ ]:
W, H, err = run_nmf(X_torch, n_components= 10, init='random', algo="halsvar", mode = "batch", 
                    beta_loss= 2.0, tol=1e-4,random_state=0,n_jobs=1, online_chunk_size = 5000)

## PyNMF

from pyDNMFk.runner import pyDNMFk_Runner
import numpy as np

In [ ]:
runner = pyDNMFk_Runner(itr=100, init='nnsvd', verbose=True, 
                        norm='fro', method='mu', precision=np.float32,
                        checkpoint=False, sill_thr=0.6)


#results = runner.run(X_torch, fpath='../data/', fname='wtsi', ftype='mat', results_path='../results/', k_range=10, step_k=1)

W = results["W"]
H = results["H"]

In [ ]:
print("X (Orginal matrix):")
print(X_torch)
print("\nW (basis matrix):")
print(W)
print("\nH (coefficient matrix):")
print(H)    
X_hat = np.dot(W, H)
print("\nX_hat (Reconstructed matrix):")
print(X_hat)